import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
test('Postgres RLS isolates sites and prevents resident privilege escalation',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema public,auth to authenticated,anon,service_role;
 grant execute on function auth.uid() to authenticated,anon,service_role;`);
 await db.exec(readFileSync('supabase/migrations/202609120001_initial.sql','utf8'));
 const owner='00000000-0000-4000-8000-000000000001', resident='00000000-0000-4000-8000-000000000002', stranger='00000000-0000-4000-8000-000000000003';
 await db.query(`insert into auth.users(id,email) values ($1,'owner@test.invalid'),($2,'resident@test.invalid'),($3,'stranger@test.invalid')`,[owner,resident,stranger]);
 async function login(id:string){await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub='${id}'`)}
 await login(owner);
 const site=(await db.query<{id:string}>("select public.create_site('Home') as id")).rows[0].id;
 await db.query('select public.add_resident($1,$2)',[site,'resident@test.invalid']);
 const device=(await db.query<{id:string}>('insert into public.devices(site_id,name,device_identifier) values($1,$2,$3) returning id',[site,'Living room','test-001'])).rows[0].id;
 await login(resident);
 assert.equal((await db.query('select * from public.sites')).rows.length,1);
 await db.query('insert into public.smell_reports(site_id,user_id,intensity) values($1,$2,4)',[site,resident]);
 await assert.rejects(db.query('insert into public.smell_reports(site_id,user_id,intensity) values($1,$2,4)',[site,owner]));
 await assert.rejects(db.query('insert into public.devices(site_id,name,device_identifier) values($1,$2,$3)',[site,'Bad','bad']));
 await assert.rejects(db.query("update public.site_members set role='owner' where user_id=$1",[resident]));
 await assert.rejects(db.query('select public.rotate_device_key($1,$2)',[device,'a'.repeat(64)]));
 await assert.rejects(db.query('select * from public.device_api_keys'));
 await assert.rejects(db.query('select public.add_resident($1,$2)',[site,'stranger@test.invalid']));
 await login(stranger);
 for(const table of ['sites','devices','site_members','smell_reports','minute_aggregates','site_state_events']) assert.equal((await db.query(`select * from public.${table}`)).rows.length,0,table);
 await assert.rejects(db.query('insert into public.site_state_events(site_id,user_id,event_type,value) values($1,$2,$3,true)',[site,stranger,'window_open']));
 await login(owner);
 await db.query('select public.rotate_device_key($1,$2)',[device,'a'.repeat(64)]);
 await db.query('select public.remove_resident($1,$2)',[site,owner]);
 assert.equal((await db.query("select * from public.site_members where role='owner'")).rows.length,1);
 await db.query('select public.remove_resident($1,$2)',[site,resident]);
 await login(resident);
 assert.equal((await db.query('select * from public.smell_reports')).rows.length,0);
 await db.close();
});
